
# Base URL Configuration
rapsodo.url=https://rapsodo.com

# Direction Url
cart.url =https://rapsodo.com/cart
golf.url=https://rapsodo.com/pages/golf

# Browser Configuration
default.browser=chrome

# Timeout Settings
implicit.wait.seconds=10
explicit.wait.seconds=10

# Screenshot Configuration
screenshot.directory=./src/test/screenshots/


